#!/bin/bash

for i in {0..1}
do
    echo "Start Iteration : $i ***********************************************************"
    ./SDX_ACCL_KERNEL_FP_VECTOR_MULT/Make_flow/fp_vector_mult.hw ../bitfiles/role/VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_KERNEL_FP_VECTOR_MULT_pblock_role_HLS_PR_NORTH_partial.bin
    VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_MATRIX_MULT_8X8_pblock_role_HLS_PR_NORTH_partial.bin*
    ./SDX_ACCL_KERNEL_PASSTHRU/Make_flow/ passthru.hw ../bitfiles/role/VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_KERNEL_PASSTHRU_pblock_role_HLS_PR_NORTH_partial.bin*
    ./SDX_ACCL_MATRIX_INVERT_4X4_CPP_KERNEL/Make_flow/matrix_inv_4x4.hw ../bitfiles/role/VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_MATRIX_INVERT_4X4_CPP_KERNEL_pblock_role_HLS_PR_NORTH_partial.bin*
    ./SDX_ACCL_MATRIX_INVERT_5X5_CPP_KERNEL/Make_flow/matrix_inv_5x5.hw ../bitfiles/role/VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_MATRIX_INVERT_5X5_CPP_KERNEL_pblock_role_HLS_PR_NORTH_partial.bin*
    ./SDX_ACCL_MATRIX_MULT_6X6/Make_flow/matrix_mult_6x6.hw ../bitfiles/role/VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_MATRIX_MULT_6X6_pblock_role_HLS_PR_NORTH_partial.bin*
    ./SDX_ACCL_MATRIX_MULT_8X8/Make_flow/matrix_mult_8x8.hw ../bitfiles/role/VU9P_AXI_ICAP_PR_DESIGN_top.IP_SDX_ACCL_MATRIX_MULT_8X8_pblock_role_HLS_PR_NORTH_partial.bin*
    echo "***************************** End Iteration : $i ***********************************************************"
done

